export const ActionTypes = {
    SET_BORROWER: "SET_BORROWER",
    SET_SELECTED_BORROWER: "SET_SELECTED_BORROWER",

    SET_BOOKS: "SET_BOOKS",
    SET_SELECTED_BOOK: "SET_SELECTED_BOOK",

    SET_STUDENTS: "SET_STUDENTS",
    SET_SELECTED_STUDENT: "SET_SELECTED_STUDENT",


}